stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - src/get_data.py
    outs:
    - processed_data/processed.csv
  
  model_Creation:
    cmd: python src/model_creation.py
    deps:
    - processed_data/processed.csv
    outs:
    - models/lr_model.pkl

  prediction:
    cmd: streamlit run src/predict.py
    deps:
    - processed_data/processed.csv
    - models/lr_model.pkl
